# Configure the application based on the environment variables
ktor:
  ## Development mode
  # Enable development mode. Recommended to set it via -Dktor.deployment.environment=development
  # development = true
  deployment:
    host: 0.0.0.0
    port: '$PORT:8080'
    ## SSL, you need to enable it
    sslPort: '$SSL_PORT:8443'
    ## Watch for changes in this directory and automatically reload the application if any file changes in development mode.
    watch:
      - classes
      - resources

  # Configure the main module
  application:
    modules:
      - ai.tech.ApplicationKt.module

  ## Environment
  environment: '$KTOR_ENV:development'

  ## To enable SSL, you need to generate a certificate and configure it here
  security:
    ssl:
      keyStore: server/src/main/resources/cert/keystore.p12
      keyStorePassword: AITech
      keyAlias: applicationTLS
      privateKeyPassword: AITech

configurations:
  - koin
  - auth
  - generate-ssl
  - cache
  - database
  - serialization
  - https-redirect
  - routing
  - websockets
  - graphql
  - call-logging
  - call-id
  - rate-limit
  - cors
  - compression
  - partial-content
  - data-conversion
  - validation
  - resources
  - status-pages
  - default-headers
  - caching-headers
  - conditional-headers
  - forwarded-headers
  - x-forwarded-headers
  - hsts
  - auto-head-response
  - x-http-method-override
  - freemarker
  - swagger
  - application-monitoring
  - micrometer-metrics
  - dropwizard-metrics
  - shutdown
