database:
  # Application Postgresql database
  app-postgresql:
    enable: true
    connection:
      protocol: r2dbc
      driver: postgresql
      host: localhost
      port: 5432
      user: user
      password: user_password
      database: app
    create-tables:
      - packages:
          - ai.tech
        if-not-exists: true

#  # Application Oracle database
#  app-oracle:
#    enable: true
#    connection:
#      protocol: r2dbc
#      driver: oracle
#      host: localhost
#      port: 1521
#      user: user
#      password: user_password
#      database: app
#    create-tables:
#      - packages:
#          - ai.tech
#        if-not-exists: true
