cors:
  enable: true
  hosts:
    - enable: true
      host: *
      schemes:
        - http
        - https
  headers:
    - Content-Type
    - Authorization
  methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
