serialization:
  enable: true
  json:
    encode-defaults: true
    is-lenient: true
    allow-special-floating-point-values: true
    allow-structured-map-keys: true
    pretty-print: false
    use-array-polymorphism: false
  xml:
  cbor:
  protobuf:
